version: '3.9'

services:
    db:
        image: postgres:16.2-alpine3.19
        container_name: database
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/postgresql/data
        ports:
            - "6432:5432"
        env_file:
            - ./.env
    web:
        build: .
        container_name: web-application
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src:/usr/src/django_project_template/src
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - db